linters:
  enable:
    - staticcheck
    - unconvert
    - gofmt
    - revive
    - ineffassign
    - vet
    - unused
    - misspell
    - bodyclose
    - errcheck
    - goimports
    - prealloc
    - gosec
    - goconst
    - gosimple
    - errname
    - gocritic
    - tparallel
    - tenv
    - unconvert
    - whitespace

run:
  deadline: 2m
  skip-dirs:
    - vendor
