linters:
  enable:
    - staticcheck
    - unconvert
    - gofmt
    - revive
    - ineffassign
    - govet
    - unused
    - misspell
    - bodyclose
    - errcheck
    - goimports
    - prealloc
    - gosec
    - goconst
    - gosimple
    - errname
    - gocritic
    - tparallel
    - usetesting
    - unconvert
    - whitespace

issues:
  exclude-dirs:
    - vendor
